"""empty message

Revision ID: 1c2c548d71a0
Revises: 7f09b82ba74f
Create Date: 2025-11-21 03:48:29.671898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1c2c548d71a0"
down_revision: Union[str, Sequence[str], None] = "7f09b82ba74f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "key")
    # ### end Alembic commands ###
