"""empty message

Revision ID: 71d60aecf1b9
Revises: df66f295b59f
Create Date: 2025-11-24 03:41:01.920858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = "71d60aecf1b9"
down_revision: Union[str, Sequence[str], None] = "df66f295b59f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
