"""empty message

Revision ID: 7f09b82ba74f
Revises: 23a1582e0e04
Create Date: 2025-11-18 03:53:26.691118

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7f09b82ba74f"
down_revision: Union[str, Sequence[str], None] = "23a1582e0e04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_projects_lang"), "projects", ["lang"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_lang"), table_name="projects")
    # ### end Alembic commands ###
