"""empty message

Revision ID: d1058df0f8ff
Revises:
Create Date: 2025-12-14 01:59:02.122441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = "d1058df0f8ff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqltypes.AutoString(), nullable=False),
        sa.Column("lang", sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqltypes.AutoString(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_lang"), "projects", ["lang"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqltypes.AutoString(), nullable=False),
        sa.Column("telegram_chat_id", sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_table(
        "envelopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("event_id", sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("dsn", sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_envelopes_id"), "envelopes", ["id"], unique=False)
    op.create_table(
        "envelope_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["envelopes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_envelope_items_id"), "envelope_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_envelope_items_item_id"), "envelope_items", ["item_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_envelope_items_item_id"), table_name="envelope_items")
    op.drop_index(op.f("ix_envelope_items_id"), table_name="envelope_items")
    op.drop_table("envelope_items")
    op.drop_index(op.f("ix_envelopes_id"), table_name="envelopes")
    op.drop_table("envelopes")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_lang"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
